feat: add tx_orderer, arrange the env variables, adjust in source code of the repo

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -108,56 +108,56 @@ services:
   #         echo "❌ Invalid MODE: ${KEY_GENERATOR_MODE}"
   #         exit 1
   #       fi
-  secure-rpc-provider:
-    build:
-      context: .
-      dockerfile: secure-rpc-provider.Dockerfile
+  # secure-rpc-provider:
+  #   build:
+  #     context: .
+  #     dockerfile: secure-rpc-provider.Dockerfile
 
-      args:
-        SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH: ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}
-        SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL: ${SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL}
-        SEQUENCER_RPC_URL: ${SEQUENCER_RPC_URL}
-        ENCRYPTED_TRANSACTION_TYPE: ${ENCRYPTED_TRANSACTION_TYPE}
-        ROLLUP_ID: ${ROLLUP_ID}
-        ROLLUP_RPC_URL: ${ROLLUP_RPC_URL}
-        SECURE_RPC_PROVIDER_PRIVATE_KEY: ${SECURE_RPC_PROVIDER_PRIVATE_KEY}
-        KEY_GENERATOR_EXTERNAL_RPC_URL: ${KEY_GENERATOR_EXTERNAL_RPC_URL}
+  #     args:
+  #       SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH: ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}
+  #       SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL: ${SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL}
+  #       SEQUENCER_RPC_URL: ${SEQUENCER_RPC_URL}
+  #       ENCRYPTED_TRANSACTION_TYPE: ${ENCRYPTED_TRANSACTION_TYPE}
+  #       ROLLUP_ID: ${ROLLUP_ID}
+  #       ROLLUP_RPC_URL: ${ROLLUP_RPC_URL}
+  #       SECURE_RPC_PROVIDER_PRIVATE_KEY: ${SECURE_RPC_PROVIDER_PRIVATE_KEY}
+  #       KEY_GENERATOR_EXTERNAL_RPC_URL: ${KEY_GENERATOR_EXTERNAL_RPC_URL}
 
-    container_name: secure-rpc-provider
+  #   container_name: secure-rpc-provider
 
-    environment:
-      SECURE_RPC_PROVIDER_MODE: ${SECURE_RPC_PROVIDER_MODE}
+  #   environment:
+  #     SECURE_RPC_PROVIDER_MODE: ${SECURE_RPC_PROVIDER_MODE}
 
-    ports:
-      - "6000:6000"
-      - "6001:6001"
+  #   ports:
+  #     - "6000:6000"
+  #     - "6001:6001"
 
-    volumes:
-      - ../secure-rpc-provider/data:/app/secure-rpc-provider/data
+  #   volumes:
+  #     - ../secure-rpc-provider/data:/app/secure-rpc-provider/data
 
-    entrypoint:
-      - "/bin/bash"
-      - "-c"
-      - |
-        # cat ./scripts/execute/env.sh
-        # cat ./scripts/execute/01_init_secure_rpc.sh
+  #   entrypoint:
+  #     - "/bin/bash"
+  #     - "-c"
+  #     - |
+  #       # cat ./scripts/execute/env.sh
+  #       # cat ./scripts/execute/01_init_secure_rpc.sh
 
-        if [ "$SECURE_RPC_PROVIDER_MODE" = "init" ]; then
-          echo "🚀 Running Secure RPC Provider Initialization..."
-          ./scripts/execute/01_init_secure_rpc.sh
-          # cat ./data/Config.toml
-          ./scripts/execute/02_run_secure_rpc.sh &
-          sleep 5
-          
-          tail -f /dev/null
+  #       if [ "$SECURE_RPC_PROVIDER_MODE" = "init" ]; then
+  #         echo "🚀 Running Secure RPC Provider Initialization..."
+  #         ./scripts/execute/01_init_secure_rpc.sh
+  #         # cat ./data/Config.toml
+  #         ./scripts/execute/02_run_secure_rpc.sh &
+  #         sleep 5
 
-        elif [ "$SECURE_RPC_PROVIDER_MODE" = "run" ]; then
-          echo "🚀 Running Secure RPC Provider..."
-          ./scripts/execute/02_run_secure_rpc.sh &
+  #         tail -f /dev/null
 
-          tail -f /dev/null
+  #       elif [ "$SECURE_RPC_PROVIDER_MODE" = "run" ]; then
+  #         echo "🚀 Running Secure RPC Provider..."
+  #         ./scripts/execute/02_run_secure_rpc.sh &
 
-        else
-          echo "❌ Invalid MODE: ${SECURE_RPC_PROVIDER_MODE}"
-          exit 1
-        fi
+  #         tail -f /dev/null
+
+  #       else
+  #         echo "❌ Invalid MODE: ${SECURE_RPC_PROVIDER_MODE}"
+  #         exit 1
+  #       fi
