add secure-rpc-provider

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -55,56 +55,109 @@ services:
   #         echo "❌ Invalid MODE: ${MODE}"
   #         exit 1
   #       fi
-  key_generator:
+  # key_generator:
+  #   build:
+  #     context: .
+  #     dockerfile: key_generator.Dockerfile
+
+  #     args:
+  #       KEY_GENERATOR_EXECUTE_ENV_PATH: ${KEY_GENERATOR_EXECUTE_ENV_PATH}
+  #       KEY_GENERATOR_RPC_CALL_ENV_PATH: ${KEY_GENERATOR_RPC_CALL_ENV_PATH}
+  #       KEY_GENERATOR_INTERNAL_RPC_URL: ${KEY_GENERATOR_INTERNAL_RPC_URL}
+  #       KEY_GENERATOR_CLUSTER_RPC_URL: ${KEY_GENERATOR_CLUSTER_RPC_URL}
+  #       KEY_GENERATOR_EXTERNAL_RPC_URL: ${KEY_GENERATOR_EXTERNAL_RPC_URL}
+  #       KEY_GENERATOR_ADDRESS: ${KEY_GENERATOR_ADDRESS}
+  #       KEY_GENERATOR_PRIVATE_KEY: ${KEY_GENERATOR_PRIVATE_KEY}
+
+  #   container_name: key_generator
+
+  #   environment:
+  #     KEY_GENERATOR_MODE: ${KEY_GENERATOR_MODE}
+
+  #   ports:
+  #     - "6000:6000"
+  #     - "6001:6001"
+
+  #   volumes:
+  #     - ../distributed_key_generation/data:/app/distributed_key_generation/data
+
+  #   entrypoint:
+  #     - "/bin/bash"
+  #     - "-c"
+  #     - |
+  #       # cat ./scripts/execute/env.sh
+  #       # cat ./scripts/execute/01_init_key_generator.sh
+
+  #       if [ "$KEY_GENERATOR_MODE" = "init" ]; then
+  #         echo "🚀 Running Key Generator Initialization..."
+  #         ./scripts/execute/01_init_key_generator.sh
+  #         # cat ./data/Config.toml
+  #         ./scripts/execute/02_run_key_generator.sh &
+  #         sleep 5
+  #         ./scripts/rpc-call/10_initialize.sh
+
+  #         tail -f /dev/null
+
+  #       elif [ "$KEY_GENERATOR_MODE" = "run" ]; then
+  #         echo "🚀 Running Key Generator..."
+  #         ./scripts/execute/02_run_key_generator.sh &
+
+  #         tail -f /dev/null
+
+  #       else
+  #         echo "❌ Invalid MODE: ${KEY_GENERATOR_MODE}"
+  #         exit 1
+  #       fi
+  secure-rpc-provider:
     build:
       context: .
-      dockerfile: key_generator.Dockerfile
+      dockerfile: secure-rpc-provider.Dockerfile
 
       args:
-        KEY_GENERATOR_EXECUTE_ENV_PATH: ${KEY_GENERATOR_EXECUTE_ENV_PATH}
-        KEY_GENERATOR_RPC_CALL_ENV_PATH: ${KEY_GENERATOR_RPC_CALL_ENV_PATH}
-        KEY_GENERATOR_INTERNAL_RPC_URL: ${KEY_GENERATOR_INTERNAL_RPC_URL}
-        KEY_GENERATOR_CLUSTER_RPC_URL: ${KEY_GENERATOR_CLUSTER_RPC_URL}
+        SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH: ${SECURE_RPC_PROVIDER_EXECUTE_ENV_PATH}
+        SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL: ${SECURE_RPC_PROVIDER_EXTERNAL_RPC_URL}
+        SEQUENCER_RPC_URL: ${SEQUENCER_RPC_URL}
+        ENCRYPTED_TRANSACTION_TYPE: ${ENCRYPTED_TRANSACTION_TYPE}
+        ROLLUP_ID: ${ROLLUP_ID}
+        ROLLUP_RPC_URL: ${ROLLUP_RPC_URL}
+        SECURE_RPC_PROVIDER_PRIVATE_KEY: ${SECURE_RPC_PROVIDER_PRIVATE_KEY}
         KEY_GENERATOR_EXTERNAL_RPC_URL: ${KEY_GENERATOR_EXTERNAL_RPC_URL}
-        KEY_GENERATOR_ADDRESS: ${KEY_GENERATOR_ADDRESS}
-        KEY_GENERATOR_PRIVATE_KEY: ${KEY_GENERATOR_PRIVATE_KEY}
 
-    container_name: key_generator
+    container_name: secure-rpc-provider
 
     environment:
-      KEY_GENERATOR_MODE: ${KEY_GENERATOR_MODE}
+      SECURE_RPC_PROVIDER_MODE: ${SECURE_RPC_PROVIDER_MODE}
 
     ports:
       - "6000:6000"
       - "6001:6001"
 
     volumes:
-      - ../distributed_key_generation./data:/app/distributed_key_generation/data
+      - ../secure-rpc-provider/data:/app/secure-rpc-provider/data
 
     entrypoint:
       - "/bin/bash"
       - "-c"
       - |
         # cat ./scripts/execute/env.sh
-        # cat ./scripts/execute/01_init_key_generator.sh
+        # cat ./scripts/execute/01_init_secure_rpc.sh
 
-        if [ "$KEY_GENERATOR_MODE" = "init" ]; then
-          echo "🚀 Running Key Generator Initialization..."
-          ./scripts/execute/01_init_key_generator.sh
+        if [ "$SECURE_RPC_PROVIDER_MODE" = "init" ]; then
+          echo "🚀 Running Secure RPC Provider Initialization..."
+          ./scripts/execute/01_init_secure_rpc.sh
           # cat ./data/Config.toml
-          ./scripts/execute/02_run_key_generator.sh &
+          ./scripts/execute/02_run_secure_rpc.sh &
           sleep 5
-          ./scripts/rpc-call/10_initialize.sh
           
           tail -f /dev/null
 
-        elif [ "$KEY_GENERATOR_MODE" = "run" ]; then
-          echo "🚀 Running Key Generator..."
-          ./scripts/execute/02_run_key_generator.sh &
+        elif [ "$SECURE_RPC_PROVIDER_MODE" = "run" ]; then
+          echo "🚀 Running Secure RPC Provider..."
+          ./scripts/execute/02_run_secure_rpc.sh &
 
           tail -f /dev/null
 
         else
-          echo "❌ Invalid MODE: ${KEY_GENERATOR_MODE}"
+          echo "❌ Invalid MODE: ${SECURE_RPC_PROVIDER_MODE}"
           exit 1
         fi
